# exclude non-core contracts from coverage analysis
reports:
  exclude_paths:
    - contracts/testing/*.*
    - contracts/gauges/*.*

hypothesis:
  phases:
    explicit: true
    reuse: true
    generate: true
    target: true
    shrink: false
